HW3
polisgo2020/Konovalov_Mihail pull request #5
Opened 2020-03-29 21:18 UTC by Mishka-technic

2020-03-30 17:38 UTC, Mishka-technic commented
@tariel-x Посмотрите пожалуйста)

2020-03-31 22:37 UTC, tariel-x requested changes
Я к прошлому решению написал несколько комментариев:

1.Необходимо сделать 2 утилиты: одна строит индекс, вторая читает. Либо как 2 пакета с функциями main, либо один но с простейшим интерфейсом выбора режима.
2. Общение с пользователем и работу с файлами лучше оставить в main.
3. Сделать в корне go mod init github.com/polisgo2020/Konovalov_Mihail.

Стоит всё же исправить проект.

2020-03-31 22:37 UTC, tariel-x commented on invertedIndex/buildInvertedIndexList.go
> +	var wg sync.WaitGroup
Лучше писать `wg := &sync.WaitGroup{}`, чтоб никогда не забывать про то, что переменная должна быть ссылочной.

2020-04-05 07:59 UTC, Mishka-technic commented
@tariel-x Теперь другая ошибка
![image](https://user-images.githubusercontent.com/42578242/78469742-8614d500-772c-11ea-8c11-48a4d9f89e96.png)

2020-04-05 08:43 UTC, Mishka-technic commented
@tariel-x  и еще вопрос, как разделить поиск и построение если они взаимосвязаны?

2020-04-05 09:04 UTC, Mishka-technic commented
Имею ввиду, что что без готовой структуры индекса, не получиться найти совпадения

2020-04-05 16:15 UTC, Mishka-technic commented
@tariel-x И еще можно вопрос по следующей работе, делать тест для проверки корректности формирования инвертированного индекса и указывать какую то директорию с файлами это плохо?

2020-04-05 21:26 UTC, Mishka-technic commented
@tariel-x И еще вопрос, вы говорите нужно перенести всю работу с файлами в main, но тогда мне придется всю утилиту по построению индекса перенести в main так как там как раз есть взаимодействие с ними, все равно перенести?

2020-04-06 17:39 UTC, Mishka-technic commented
@tariel-x Возможно вы имели ввиду мои вопросы)

2020-04-08 08:54 UTC, Mishka-technic commented
@tariel-x Вы наверное по меня забыли(

2020-04-08 16:37 UTC, tariel-x commented
> @tariel-x и еще вопрос, как разделить поиск и построение если они взаимосвязаны?

Логику поиска и построения разделять не стоит, этот код можно вынести в отдельную библиотеку.

2020-04-08 17:06 UTC, tariel-x commented
> Имею ввиду, что что без готовой структуры индекса, не получиться найти совпадения

Две разные утилиты могут использовать один и тот же пакет: одна для построения и сохранения, другая для чтения и поиска. Разделить их очень просто, если общая логика вынесена в один пакет.

2020-04-08 17:07 UTC, Mishka-technic commented
Так а у меня же вроде итак так и есть?

2020-04-08 17:14 UTC, tariel-x commented
> @tariel-x И еще можно вопрос по следующей работе, делать тест для проверки корректности формирования инвертированного индекса и указывать какую то директорию с файлами это плохо?

Смотря какая реализация теста. Вообще тестами покрываются отдельные функции. Если отделить чтение файла от его обработки, то можно покрыть тестом обработку теста, обработу токенов, а само чтение можно не покрывать.

2020-04-08 17:44 UTC, tariel-x commented
> @tariel-x Теперь другая ошибка
> ![image](https://user-images.githubusercontent.com/42578242/78469742-8614d500-772c-11ea-8c11-48a4d9f89e96.png)

Попробуйте в терминале просто ввести `go build` и посмотрим, что получится.

2020-04-08 17:48 UTC, tariel-x commented
> Так а у меня же вроде итак так и есть?

Нет, необходимо сделать так, чтоб можно было либо создать файл, либо прочитать его и использовать.

2020-04-10 10:48 UTC, Mishka-technic commented
@tariel-x  А что значит прочитать и использовать не очень понимаю?

2020-04-10 10:49 UTC, Mishka-technic commented
@tariel-x Вот что при build пишет
![image](https://user-images.githubusercontent.com/42578242/78985667-09ba3180-7b32-11ea-9a96-7dfc5acc2045.png)

2020-04-10 13:55 UTC, Mishka-technic commented
@tariel-x Вроде разобрался с проблемами и со структурой проекта, посмотрите пожалуйста)

2020-04-10 14:12 UTC, Mishka-technic commented
Ой, забыл чтение перенести в main(

2020-04-10 20:50 UTC, Mishka-technic commented
Или в принципе итак все в порядке?

2020-04-10 22:28 UTC, tariel-x commented
> @tariel-x А что значит прочитать и использовать не очень понимаю?
> Просто у меня для поиска нужно в любом случае иметь структуру данных с инвертированным индексом.

Если у вас есть гигабайт файлов с текстами и нужно регулярно осуществлять полнотекстовый поиск по ним, то:
1. необходимо прочитать все эти файлы
2. построить в памяти обратный индекс
3. сохранить индекс в на диск

Затем при запуске поиска достаточно прочитать значительно меньший по объёму индекс и выполнять по нему поиск. Исходные файлы при этом перечитывать не нужно.

Сейчас же в main.go:26 происходит перечитывание исходных файлов в любом случае.

2020-04-11 11:37 UTC, Mishka-technic commented
@tariel-x  А тогда получается нам нужно будет поиск осуществлять перечитывая все файлы заново, да может с гораздо меньшим объемом, но по факту, а зачем нам два раза с файла читать если  после построения индекса у нас все в структуре уже храниться в программе?

2020-04-11 16:09 UTC, tariel-x commented
> @tariel-x А тогда получается нам нужно будет поиск осуществлять перечитывая все файлы заново, да может с гораздо меньшим объемом, но по факту, а зачем нам два раза с файла читать если после построения индекса у нас все в структуре уже храниться в программе?

Потому что когда индекс построен и сохранён на диске, программу можно завершить. И запустить в следующий раз. Тогда программа после повторного запуска прочитает файл с индексом. Ведь после повторного запуска у неё в памяти нет никаких данных.

2020-04-11 17:04 UTC, Mishka-technic commented
Все понял)

2020-04-11 20:14 UTC, Mishka-technic commented
@tariel-x Посмотрите пожалуйста, сделал)

2020-04-14 19:04 UTC, tariel-x reviewed
Я уже хотел зачесть, но теперь сломался поиск :pensive:

```
$ go run -race main.go search index.data.txt
panic: runtime error: index out of range [6] with length 6

goroutine 7 [running]:
github.com/polisgo2020/Konovalov_Mihail/invertedIndex.parseString(0xc000380017, 0x3d, 0x0)
        /home/nikita/go/src/github.com/polisgo2020/Konovalov_Mihail/invertedIndex/searchBestStringMatch.go:117 +0x949
github.com/polisgo2020/Konovalov_Mihail/invertedIndex.writeString(0xc000380017, 0x3d, 0xc000028060, 0xc00001c100)
        /home/nikita/go/src/github.com/polisgo2020/Konovalov_Mihail/invertedIndex/searchBestStringMatch.go:94 +0x80
created by github.com/polisgo2020/Konovalov_Mihail/invertedIndex.readFileWithInvertedIndex
        /home/nikita/go/src/github.com/polisgo2020/Konovalov_Mihail/invertedIndex/searchBestStringMatch.go:70 +0x28c
exit status 2
```

Индекс строил так:
```
$ go run -race main.go create ~/go/src/github.com/polisgo2020/main/books/ index.data
```

Кстати, кажется, строить индекс для каждого файла отдельно и мержить их потом кажется не очень оптимально, потому что код работал подозрительно долго. Но, наверное, сойдёт.

2020-04-14 20:01 UTC, Mishka-technic commented
@tariel-x А вы какие данные использовали?

2020-04-14 20:04 UTC, Mishka-technic commented
А, вы в поисковую строку ничего не вбили, сейчас пофикшу

2020-04-14 20:05 UTC, Mishka-technic commented
Хотя я понял что проблема не в этом

2020-04-14 20:21 UTC, Mishka-technic commented
@tariel-x все пофиксил, посмотрите пожалуйста

2020-04-15 18:14 UTC, tariel-x approved these changes

2020-04-15 18:16 UTC, tariel-x commented
Один только минус остался - невысокая скорость работы, несмотря на параллельную обработку.

2020-04-15 19:06 UTC, Mishka-technic commented
Я честно говоря не знаю как его пофиксить, да и времени мне уже не хватит видимо

2020-04-15 19:07 UTC, merged